-- =============================================================================
-- Step 7B / 45 - Create the PostGIS 3.6.2 extension in schema postgis
-- =============================================================================
-- GENERATED by scripts/step7_postgis_experiment.py - do not edit by hand. Run by sql/run_step7b_postgis_setup.ps1.
-- Plan: docs/Step7B_PostGIS_Setup_Preflight.md (approved).
-- One transaction. Guard (LR019): postgis 3.6.2 available and not installed; pg_extension = {plpgsql}; schemas postgis
-- and log_regex_gis absent; no geometry/geography type; superuser. Gate X-01 .. X-06 before COMMIT (LR019).
-- =============================================================================

\set ON_ERROR_STOP on
SET client_encoding = 'UTF8';

BEGIN;
SET LOCAL lock_timeout = '10s';

DO $guard$
BEGIN
    IF (SELECT default_version FROM pg_available_extensions WHERE name = 'postgis') IS DISTINCT FROM '3.6.2'
       OR (SELECT installed_version FROM pg_available_extensions WHERE name = 'postgis') IS NOT NULL
       OR (SELECT string_agg(extname, ',' ORDER BY extname) FROM pg_extension) IS DISTINCT FROM 'plpgsql'
       OR to_regnamespace('postgis') IS NOT NULL OR to_regnamespace('log_regex_gis') IS NOT NULL
       OR EXISTS (SELECT 1 FROM pg_type WHERE typname IN ('geometry', 'geography'))
       OR NOT current_setting('is_superuser')::boolean THEN
        RAISE EXCEPTION 'sql/45 refused: PostGIS 3.6.2 not available, already installed, or the database is not in the verified pre-setup state'
            USING ERRCODE = 'LR019';
    END IF;
END
$guard$;

CREATE SCHEMA postgis;
CREATE EXTENSION postgis WITH SCHEMA postgis VERSION '3.6.2';

SELECT set_config('step7b.gate45', '0', false) AS reset \gset x_
DO $gate$
DECLARE
    v_failed integer := coalesce(nullif(current_setting('step7b.gate45', true), ''), '0')::integer;
    chk      record;
BEGIN
    FOR chk IN
        SELECT c.id, c.name, c.expected, c.actual
        FROM (VALUES
            ('X-01', 'installed extensions', 'plpgsql 1.0 pg_catalog, postgis 3.6.2 postgis', (SELECT string_agg(extname || ' ' || extversion || ' ' || extnamespace::regnamespace::text, ', ' ORDER BY extname) FROM pg_extension)),
            ('X-02', 'postgis_lib_version()', '3.6.2', (SELECT postgis.postgis_lib_version())),
            ('X-03', 'spatial_ref_sys SRID 4326 authority', 'EPSG/4326', (SELECT auth_name || '/' || auth_srid FROM postgis.spatial_ref_sys WHERE srid = 4326)),
            ('X-04', 'operator classes of the design in schema postgis', 'brin_geometry_inclusion_ops_2d,gist_geography_ops,gist_geometry_ops_2d,spgist_geography_ops_nd,spgist_geometry_ops_2d', (SELECT string_agg(opcname, ',' ORDER BY opcname COLLATE "C") FROM pg_opclass WHERE opcnamespace = 'postgis'::regnamespace AND opcname IN ('brin_geometry_inclusion_ops_2d', 'gist_geography_ops', 'gist_geometry_ops_2d', 'spgist_geography_ops_nd', 'spgist_geometry_ops_2d'))),
            ('X-05', 'IMMUTABLE: ST_MakePoint(float8, float8) / ST_SetSRID(geometry, integer) / geography(geometry)', 'i/i/i', ((SELECT provolatile::text FROM pg_proc WHERE oid = 'postgis.st_makepoint(double precision, double precision)'::regprocedure) || '/' || (SELECT provolatile::text FROM pg_proc WHERE oid = 'postgis.st_setsrid(postgis.geometry, integer)'::regprocedure) || '/' || (SELECT provolatile::text FROM pg_proc WHERE oid = 'postgis.geography(postgis.geometry)'::regprocedure))),
            ('X-06', 'schemas | public relations/functions/types | event triggers', 'log_regex,log_regex_json,log_regex_json_write,postgis,public|0/0/0|0', ((SELECT string_agg(nspname, ',' ORDER BY nspname COLLATE "C") FROM pg_namespace WHERE nspname NOT LIKE 'pg\_%' AND nspname <> 'information_schema') || '|' || (SELECT count(*) FROM pg_class WHERE relnamespace = 'public'::regnamespace) || '/' || (SELECT count(*) FROM pg_proc WHERE pronamespace = 'public'::regnamespace) || '/' || (SELECT count(*) FROM pg_type WHERE typnamespace = 'public'::regnamespace) || '|' || (SELECT count(*) FROM pg_event_trigger)))
        ) AS c (id, name, expected, actual)
    LOOP
        IF chk.expected IS NOT DISTINCT FROM chk.actual THEN
            RAISE NOTICE '% PASS  %: %', chk.id, chk.name, chk.actual;
        ELSE
            v_failed := v_failed + 1;
            RAISE WARNING '% FAIL  %: expected %, actual %', chk.id, chk.name, chk.expected, chk.actual;
        END IF;
    END LOOP;
    PERFORM set_config('step7b.gate45', v_failed::text, false);
END
$gate$;
DO $verdict$
BEGIN
    IF current_setting('step7b.gate45')::integer > 0 THEN
        RAISE EXCEPTION 'sql/45 extension gate FAILED: % of 6 checks', current_setting('step7b.gate45') USING ERRCODE = 'LR019';
    END IF;
    RAISE NOTICE 'sql/45 extension gate PASSED: all 6 checks';
END
$verdict$;

COMMIT;
