-- =============================================================================
-- Step 7B / 46 - Create schema log_regex_gis and the 15 experiment tables
-- =============================================================================
-- GENERATED by scripts/step7_postgis_experiment.py - do not edit by hand. Run by sql/run_step7b_postgis_setup.ps1.
-- Plan: docs/Step7B_PostGIS_Setup_Preflight.md (approved).
-- One transaction. Guard (LR020): log_regex_gis absent; postgis 3.6.2 installed in schema postgis; sources present.
-- Each source is read exactly once (access_log_flat -> flat_numeric, access_log_jsonb -> jsonb_doc); all other tables
-- load from these copies. Points: postgis.ST_MakePoint(longitude, latitude), SRID 4326. No secondary index.
-- Gate O-1 / O-7 before COMMIT (LR020); VACUUM (ANALYZE) of the 15 tables after COMMIT.
-- =============================================================================

\set ON_ERROR_STOP on
SET client_encoding = 'UTF8';

BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL search_path = log_regex_gis, postgis;

DO $guard$
BEGIN
    IF to_regnamespace('log_regex_gis') IS NOT NULL
       OR (SELECT extversion || ' ' || extnamespace::regnamespace::text FROM pg_extension WHERE extname = 'postgis') IS DISTINCT FROM '3.6.2 postgis'
       OR to_regclass('log_regex.access_log_flat') IS NULL OR to_regclass('log_regex_json.access_log_jsonb') IS NULL THEN
        RAISE EXCEPTION 'sql/46 refused: schema log_regex_gis exists, PostGIS 3.6.2 is not installed in schema postgis, or a source table is missing'
            USING ERRCODE = 'LR020';
    END IF;
END
$guard$;

CREATE SCHEMA log_regex_gis;

CREATE TABLE log_regex_gis.flat_numeric (
    log_id integer NOT NULL,
    latitude_degrees  numeric(10,7),
    longitude_degrees numeric(10,7),
    CONSTRAINT flat_numeric_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.flat_numeric_btree (
    log_id integer NOT NULL,
    latitude_degrees  numeric(10,7),
    longitude_degrees numeric(10,7),
    CONSTRAINT flat_numeric_btree_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.flat_geom (
    log_id integer NOT NULL,
    geom   postgis.geometry(Point, 4326),
    CONSTRAINT flat_geom_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.flat_geom_gist (
    log_id integer NOT NULL,
    geom   postgis.geometry(Point, 4326),
    CONSTRAINT flat_geom_gist_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.flat_geom_spgist (
    log_id integer NOT NULL,
    geom   postgis.geometry(Point, 4326),
    CONSTRAINT flat_geom_spgist_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.flat_geom_brin (
    log_id integer NOT NULL,
    geom   postgis.geometry(Point, 4326),
    CONSTRAINT flat_geom_brin_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.flat_geog (
    log_id integer NOT NULL,
    geog   postgis.geography(Point, 4326),
    CONSTRAINT flat_geog_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.flat_geog_gist (
    log_id integer NOT NULL,
    geog   postgis.geography(Point, 4326),
    CONSTRAINT flat_geog_gist_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.flat_geog_spgist (
    log_id integer NOT NULL,
    geog   postgis.geography(Point, 4326),
    CONSTRAINT flat_geog_spgist_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.jsonb_doc (
    log_id integer NOT NULL,
    doc    jsonb   NOT NULL,
    CONSTRAINT jsonb_doc_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.jsonb_doc_expr (
    log_id integer NOT NULL,
    doc    jsonb   NOT NULL,
    CONSTRAINT jsonb_doc_expr_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.jsonb_geom (
    log_id integer NOT NULL,
    doc    jsonb   NOT NULL,
    geom   postgis.geometry(Point, 4326) GENERATED ALWAYS AS (postgis.ST_SetSRID(postgis.ST_MakePoint((doc->'fields'->'longitude'->>'degrees')::float8, (doc->'fields'->'latitude'->>'degrees')::float8), 4326)) STORED,
    CONSTRAINT jsonb_geom_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.jsonb_geom_gist (
    log_id integer NOT NULL,
    doc    jsonb   NOT NULL,
    geom   postgis.geometry(Point, 4326) GENERATED ALWAYS AS (postgis.ST_SetSRID(postgis.ST_MakePoint((doc->'fields'->'longitude'->>'degrees')::float8, (doc->'fields'->'latitude'->>'degrees')::float8), 4326)) STORED,
    CONSTRAINT jsonb_geom_gist_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.jsonb_geog (
    log_id integer NOT NULL,
    doc    jsonb   NOT NULL,
    geog   postgis.geography(Point, 4326) GENERATED ALWAYS AS (postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((doc->'fields'->'longitude'->>'degrees')::float8, (doc->'fields'->'latitude'->>'degrees')::float8), 4326))) STORED,
    CONSTRAINT jsonb_geog_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

CREATE TABLE log_regex_gis.jsonb_geog_gist (
    log_id integer NOT NULL,
    doc    jsonb   NOT NULL,
    geog   postgis.geography(Point, 4326) GENERATED ALWAYS AS (postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((doc->'fields'->'longitude'->>'degrees')::float8, (doc->'fields'->'latitude'->>'degrees')::float8), 4326))) STORED,
    CONSTRAINT jsonb_geog_gist_pkey PRIMARY KEY (log_id)
) WITH (autovacuum_enabled = false);

-- loads: the two source reads first, then the copies
INSERT INTO log_regex_gis.flat_numeric (log_id, latitude_degrees, longitude_degrees)
SELECT log_id, latitude_degrees, longitude_degrees FROM log_regex.access_log_flat ORDER BY log_id;

INSERT INTO log_regex_gis.flat_numeric_btree (log_id, latitude_degrees, longitude_degrees)
SELECT log_id, latitude_degrees, longitude_degrees FROM log_regex_gis.flat_numeric ORDER BY log_id;

INSERT INTO log_regex_gis.flat_geom (log_id, geom)
SELECT log_id, postgis.ST_SetSRID(postgis.ST_MakePoint(longitude_degrees::float8, latitude_degrees::float8), 4326) FROM log_regex_gis.flat_numeric ORDER BY log_id;

INSERT INTO log_regex_gis.flat_geom_gist (log_id, geom)
SELECT log_id, postgis.ST_SetSRID(postgis.ST_MakePoint(longitude_degrees::float8, latitude_degrees::float8), 4326) FROM log_regex_gis.flat_numeric ORDER BY log_id;

INSERT INTO log_regex_gis.flat_geom_spgist (log_id, geom)
SELECT log_id, postgis.ST_SetSRID(postgis.ST_MakePoint(longitude_degrees::float8, latitude_degrees::float8), 4326) FROM log_regex_gis.flat_numeric ORDER BY log_id;

INSERT INTO log_regex_gis.flat_geom_brin (log_id, geom)
SELECT log_id, postgis.ST_SetSRID(postgis.ST_MakePoint(longitude_degrees::float8, latitude_degrees::float8), 4326) FROM log_regex_gis.flat_numeric ORDER BY log_id;

INSERT INTO log_regex_gis.flat_geog (log_id, geog)
SELECT log_id, postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint(longitude_degrees::float8, latitude_degrees::float8), 4326)) FROM log_regex_gis.flat_numeric ORDER BY log_id;

INSERT INTO log_regex_gis.flat_geog_gist (log_id, geog)
SELECT log_id, postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint(longitude_degrees::float8, latitude_degrees::float8), 4326)) FROM log_regex_gis.flat_numeric ORDER BY log_id;

INSERT INTO log_regex_gis.flat_geog_spgist (log_id, geog)
SELECT log_id, postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint(longitude_degrees::float8, latitude_degrees::float8), 4326)) FROM log_regex_gis.flat_numeric ORDER BY log_id;

INSERT INTO log_regex_gis.jsonb_doc (log_id, doc)
SELECT log_id, doc FROM log_regex_json.access_log_jsonb ORDER BY log_id;

INSERT INTO log_regex_gis.jsonb_doc_expr (log_id, doc)
SELECT log_id, doc FROM log_regex_gis.jsonb_doc ORDER BY log_id;

INSERT INTO log_regex_gis.jsonb_geom (log_id, doc)
SELECT log_id, doc FROM log_regex_gis.jsonb_doc ORDER BY log_id;

INSERT INTO log_regex_gis.jsonb_geom_gist (log_id, doc)
SELECT log_id, doc FROM log_regex_gis.jsonb_doc ORDER BY log_id;

INSERT INTO log_regex_gis.jsonb_geog (log_id, doc)
SELECT log_id, doc FROM log_regex_gis.jsonb_doc ORDER BY log_id;

INSERT INTO log_regex_gis.jsonb_geog_gist (log_id, doc)
SELECT log_id, doc FROM log_regex_gis.jsonb_doc ORDER BY log_id;

SELECT set_config('step7b.gate46', '0', false) AS reset \gset x_
DO $gate$
DECLARE
    v_failed integer := coalesce(nullif(current_setting('step7b.gate46', true), ''), '0')::integer;
    chk      record;
BEGIN
    FOR chk IN
        SELECT c.id, c.name, c.expected, c.actual
        FROM (VALUES
            ('O-1a:flat_numeric', 'flat_numeric: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.flat_numeric t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:flat_numeric_btree', 'flat_numeric_btree: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.flat_numeric_btree t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:flat_geom', 'flat_geom: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.flat_geom t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:flat_geom_gist', 'flat_geom_gist: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.flat_geom_gist t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:flat_geom_spgist', 'flat_geom_spgist: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.flat_geom_spgist t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:flat_geom_brin', 'flat_geom_brin: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.flat_geom_brin t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:flat_geog', 'flat_geog: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.flat_geog t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:flat_geog_gist', 'flat_geog_gist: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.flat_geog_gist t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:flat_geog_spgist', 'flat_geog_spgist: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.flat_geog_spgist t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:jsonb_doc', 'jsonb_doc: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.jsonb_doc t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:jsonb_doc_expr', 'jsonb_doc_expr: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.jsonb_doc_expr t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:jsonb_geom', 'jsonb_geom: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.jsonb_geom t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:jsonb_geom_gist', 'jsonb_geom_gist: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.jsonb_geom_gist t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:jsonb_geog', 'jsonb_geog: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.jsonb_geog t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1a:jsonb_geog_gist', 'jsonb_geog_gist: 5,000 rows, log_id set = flat_numeric (rows/unmatched)', '5000/0', (SELECT count(*) || '/' || count(*) FILTER (WHERE t.log_id IS NULL OR f.log_id IS NULL) FROM log_regex_gis.jsonb_geog_gist t FULL JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:flat_geom', 'flat_geom: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geom IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geom IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.flat_geom t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:flat_geom', 'flat_geom: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y(t.geom)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.flat_geom t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:flat_geom', 'flat_geom: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geom) = 4326 AND postgis.GeometryType(t.geom) = 'POINT' AND postgis.ST_IsValid(t.geom))::text FROM log_regex_gis.flat_geom t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:flat_geom', 'flat_geom: byte-identical to flat_geom (EWKB)', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB(t.geom) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom))::text FROM log_regex_gis.flat_geom t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:flat_geom', 'flat_geom: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y(t.geom)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y(t.geom)::numeric, 7) || ',' || round(postgis.ST_X(t.geom)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.flat_geom t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:flat_geom_gist', 'flat_geom_gist: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geom IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geom IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.flat_geom_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:flat_geom_gist', 'flat_geom_gist: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y(t.geom)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.flat_geom_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:flat_geom_gist', 'flat_geom_gist: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geom) = 4326 AND postgis.GeometryType(t.geom) = 'POINT' AND postgis.ST_IsValid(t.geom))::text FROM log_regex_gis.flat_geom_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:flat_geom_gist', 'flat_geom_gist: byte-identical to flat_geom (EWKB)', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB(t.geom) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom))::text FROM log_regex_gis.flat_geom_gist t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:flat_geom_gist', 'flat_geom_gist: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y(t.geom)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y(t.geom)::numeric, 7) || ',' || round(postgis.ST_X(t.geom)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.flat_geom_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:flat_geom_spgist', 'flat_geom_spgist: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geom IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geom IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.flat_geom_spgist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:flat_geom_spgist', 'flat_geom_spgist: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y(t.geom)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.flat_geom_spgist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:flat_geom_spgist', 'flat_geom_spgist: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geom) = 4326 AND postgis.GeometryType(t.geom) = 'POINT' AND postgis.ST_IsValid(t.geom))::text FROM log_regex_gis.flat_geom_spgist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:flat_geom_spgist', 'flat_geom_spgist: byte-identical to flat_geom (EWKB)', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB(t.geom) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom))::text FROM log_regex_gis.flat_geom_spgist t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:flat_geom_spgist', 'flat_geom_spgist: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y(t.geom)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y(t.geom)::numeric, 7) || ',' || round(postgis.ST_X(t.geom)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.flat_geom_spgist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:flat_geom_brin', 'flat_geom_brin: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geom IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geom IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.flat_geom_brin t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:flat_geom_brin', 'flat_geom_brin: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y(t.geom)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.flat_geom_brin t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:flat_geom_brin', 'flat_geom_brin: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geom) = 4326 AND postgis.GeometryType(t.geom) = 'POINT' AND postgis.ST_IsValid(t.geom))::text FROM log_regex_gis.flat_geom_brin t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:flat_geom_brin', 'flat_geom_brin: byte-identical to flat_geom (EWKB)', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB(t.geom) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom))::text FROM log_regex_gis.flat_geom_brin t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:flat_geom_brin', 'flat_geom_brin: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y(t.geom)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y(t.geom)::numeric, 7) || ',' || round(postgis.ST_X(t.geom)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.flat_geom_brin t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:jsonb_geom', 'jsonb_geom: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geom IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geom IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.jsonb_geom t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:jsonb_geom', 'jsonb_geom: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y(t.geom)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.jsonb_geom t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:jsonb_geom', 'jsonb_geom: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geom) = 4326 AND postgis.GeometryType(t.geom) = 'POINT' AND postgis.ST_IsValid(t.geom))::text FROM log_regex_gis.jsonb_geom t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:jsonb_geom', 'jsonb_geom: byte-identical to flat_geom (EWKB)', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB(t.geom) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom))::text FROM log_regex_gis.jsonb_geom t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:jsonb_geom', 'jsonb_geom: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y(t.geom)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y(t.geom)::numeric, 7) || ',' || round(postgis.ST_X(t.geom)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.jsonb_geom t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:jsonb_geom_gist', 'jsonb_geom_gist: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geom IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geom IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.jsonb_geom_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:jsonb_geom_gist', 'jsonb_geom_gist: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y(t.geom)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.jsonb_geom_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:jsonb_geom_gist', 'jsonb_geom_gist: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geom) = 4326 AND postgis.GeometryType(t.geom) = 'POINT' AND postgis.ST_IsValid(t.geom))::text FROM log_regex_gis.jsonb_geom_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:jsonb_geom_gist', 'jsonb_geom_gist: byte-identical to flat_geom (EWKB)', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB(t.geom) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom))::text FROM log_regex_gis.jsonb_geom_gist t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:jsonb_geom_gist', 'jsonb_geom_gist: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X(t.geom)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y(t.geom)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y(t.geom)::numeric, 7) || ',' || round(postgis.ST_X(t.geom)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.jsonb_geom_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:jsonb_doc_expr:geom', 'jsonb_doc_expr:geom: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326) IS NOT NULL) || '/' || count(*) FILTER (WHERE (postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326) IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:jsonb_doc_expr:geom', 'jsonb_doc_expr:geom: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326))::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326))::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:jsonb_doc_expr:geom', 'jsonb_doc_expr:geom: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)) = 4326 AND postgis.GeometryType(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)) = 'POINT' AND postgis.ST_IsValid(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::text FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:jsonb_doc_expr:geom', 'jsonb_doc_expr:geom: byte-identical to flat_geom (EWKB)', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom))::text FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:jsonb_doc_expr:geom', 'jsonb_doc_expr:geom: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326))::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326))) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326))::numeric, 7) || ',' || round(postgis.ST_X(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326))::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:flat_geog', 'flat_geog: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geog IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geog IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.flat_geog t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:flat_geog', 'flat_geog: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.flat_geog t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:flat_geog', 'flat_geog: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geog) = 4326 AND postgis.GeometryType((t.geog)::postgis.geometry) = 'POINT' AND postgis.ST_IsValid((t.geog)::postgis.geometry))::text FROM log_regex_gis.flat_geog t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:flat_geog', 'flat_geog: byte-identical to flat_geom (EWKB; geography binary = geography(flat_geom))', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB((t.geog)::postgis.geometry) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom) AND postgis.ST_AsBinary(t.geog) IS NOT DISTINCT FROM postgis.ST_AsBinary(postgis.geography(r.geom)))::text FROM log_regex_gis.flat_geog t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:flat_geog', 'flat_geog: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y((t.geog)::postgis.geometry)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) || ',' || round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.flat_geog t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:flat_geog_gist', 'flat_geog_gist: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geog IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geog IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.flat_geog_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:flat_geog_gist', 'flat_geog_gist: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.flat_geog_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:flat_geog_gist', 'flat_geog_gist: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geog) = 4326 AND postgis.GeometryType((t.geog)::postgis.geometry) = 'POINT' AND postgis.ST_IsValid((t.geog)::postgis.geometry))::text FROM log_regex_gis.flat_geog_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:flat_geog_gist', 'flat_geog_gist: byte-identical to flat_geom (EWKB; geography binary = geography(flat_geom))', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB((t.geog)::postgis.geometry) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom) AND postgis.ST_AsBinary(t.geog) IS NOT DISTINCT FROM postgis.ST_AsBinary(postgis.geography(r.geom)))::text FROM log_regex_gis.flat_geog_gist t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:flat_geog_gist', 'flat_geog_gist: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y((t.geog)::postgis.geometry)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) || ',' || round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.flat_geog_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:flat_geog_spgist', 'flat_geog_spgist: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geog IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geog IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.flat_geog_spgist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:flat_geog_spgist', 'flat_geog_spgist: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.flat_geog_spgist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:flat_geog_spgist', 'flat_geog_spgist: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geog) = 4326 AND postgis.GeometryType((t.geog)::postgis.geometry) = 'POINT' AND postgis.ST_IsValid((t.geog)::postgis.geometry))::text FROM log_regex_gis.flat_geog_spgist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:flat_geog_spgist', 'flat_geog_spgist: byte-identical to flat_geom (EWKB; geography binary = geography(flat_geom))', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB((t.geog)::postgis.geometry) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom) AND postgis.ST_AsBinary(t.geog) IS NOT DISTINCT FROM postgis.ST_AsBinary(postgis.geography(r.geom)))::text FROM log_regex_gis.flat_geog_spgist t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:flat_geog_spgist', 'flat_geog_spgist: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y((t.geog)::postgis.geometry)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) || ',' || round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.flat_geog_spgist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:jsonb_geog', 'jsonb_geog: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geog IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geog IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.jsonb_geog t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:jsonb_geog', 'jsonb_geog: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.jsonb_geog t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:jsonb_geog', 'jsonb_geog: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geog) = 4326 AND postgis.GeometryType((t.geog)::postgis.geometry) = 'POINT' AND postgis.ST_IsValid((t.geog)::postgis.geometry))::text FROM log_regex_gis.jsonb_geog t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:jsonb_geog', 'jsonb_geog: byte-identical to flat_geom (EWKB; geography binary = geography(flat_geom))', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB((t.geog)::postgis.geometry) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom) AND postgis.ST_AsBinary(t.geog) IS NOT DISTINCT FROM postgis.ST_AsBinary(postgis.geography(r.geom)))::text FROM log_regex_gis.jsonb_geog t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:jsonb_geog', 'jsonb_geog: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y((t.geog)::postgis.geometry)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) || ',' || round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.jsonb_geog t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:jsonb_geog_gist', 'jsonb_geog_gist: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE t.geog IS NOT NULL) || '/' || count(*) FILTER (WHERE (t.geog IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.jsonb_geog_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:jsonb_geog_gist', 'jsonb_geog_gist: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.jsonb_geog_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:jsonb_geog_gist', 'jsonb_geog_gist: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(t.geog) = 4326 AND postgis.GeometryType((t.geog)::postgis.geometry) = 'POINT' AND postgis.ST_IsValid((t.geog)::postgis.geometry))::text FROM log_regex_gis.jsonb_geog_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:jsonb_geog_gist', 'jsonb_geog_gist: byte-identical to flat_geom (EWKB; geography binary = geography(flat_geom))', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB((t.geog)::postgis.geometry) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom) AND postgis.ST_AsBinary(t.geog) IS NOT DISTINCT FROM postgis.ST_AsBinary(postgis.geography(r.geom)))::text FROM log_regex_gis.jsonb_geog_gist t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:jsonb_geog_gist', 'jsonb_geog_gist: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y((t.geog)::postgis.geometry)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y((t.geog)::postgis.geometry)::numeric, 7) || ',' || round(postgis.ST_X((t.geog)::postgis.geometry)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.jsonb_geog_gist t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1b:jsonb_doc_expr:geog', 'jsonb_doc_expr:geog: non-NULL points / NULL where the flat pair is not both VALID (mismatches)', '4161/0', (SELECT count(*) FILTER (WHERE postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)) IS NOT NULL) || '/' || count(*) FILTER (WHERE (postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)) IS NULL) <> (f.latitude_degrees IS NULL OR f.longitude_degrees IS NULL)) FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1c:jsonb_doc_expr:geog', 'jsonb_doc_expr:geog: exact coordinates, round(ST_X,7) = longitude and round(ST_Y,7) = latitude', '4161', (SELECT count(*) FILTER (WHERE round(postgis.ST_X((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::postgis.geometry)::numeric, 7) = f.longitude_degrees AND round(postgis.ST_Y((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::postgis.geometry)::numeric, 7) = f.latitude_degrees)::text FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d:jsonb_doc_expr:geog', 'jsonb_doc_expr:geog: SRID 4326, GeometryType POINT, ST_IsValid', '4161', (SELECT count(*) FILTER (WHERE postgis.ST_SRID(postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326))) = 4326 AND postgis.GeometryType((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::postgis.geometry) = 'POINT' AND postgis.ST_IsValid((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::postgis.geometry))::text FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1e:jsonb_doc_expr:geog', 'jsonb_doc_expr:geog: byte-identical to flat_geom (EWKB; geography binary = geography(flat_geom))', '5000', (SELECT count(*) FILTER (WHERE postgis.ST_AsEWKB((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::postgis.geometry) IS NOT DISTINCT FROM postgis.ST_AsEWKB(r.geom) AND postgis.ST_AsBinary(postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326))) IS NOT DISTINCT FROM postgis.ST_AsBinary(postgis.geography(r.geom)))::text FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_geom r ON r.log_id = t.log_id)),
            ('O-1f:jsonb_doc_expr:geog', 'jsonb_doc_expr:geog: axis order (|longitude| > 90 points with ST_X = longitude, |ST_Y| <= 90) | boundary rows', '856|2122=0.0000000,0.0000000;2272=90.0000000,180.0000000;2280=-90.0000000,-180.0000000', (SELECT count(*) FILTER (WHERE abs(f.longitude_degrees) > 90 AND round(postgis.ST_X((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::postgis.geometry)::numeric, 7) = f.longitude_degrees AND abs(postgis.ST_Y((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::postgis.geometry)) <= 90) || '|' || string_agg(t.log_id || '=' || round(postgis.ST_Y((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::postgis.geometry)::numeric, 7) || ',' || round(postgis.ST_X((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((t.doc->'fields'->'longitude'->>'degrees')::float8, (t.doc->'fields'->'latitude'->>'degrees')::float8), 4326)))::postgis.geometry)::numeric, 7), ';' ORDER BY t.log_id) FILTER (WHERE t.log_id IN (2122, 2272, 2280)) FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id)),
            ('O-1d-type:flat_geom', 'flat_geom.geom column type is geometry(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geometry[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.flat_geom'::regclass AND a.attname = 'geom')),
            ('O-1d-type:flat_geom_gist', 'flat_geom_gist.geom column type is geometry(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geometry[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.flat_geom_gist'::regclass AND a.attname = 'geom')),
            ('O-1d-type:flat_geom_spgist', 'flat_geom_spgist.geom column type is geometry(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geometry[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.flat_geom_spgist'::regclass AND a.attname = 'geom')),
            ('O-1d-type:flat_geom_brin', 'flat_geom_brin.geom column type is geometry(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geometry[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.flat_geom_brin'::regclass AND a.attname = 'geom')),
            ('O-1d-type:jsonb_geom', 'jsonb_geom.geom column type is geometry(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geometry[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.jsonb_geom'::regclass AND a.attname = 'geom')),
            ('O-1d-type:jsonb_geom_gist', 'jsonb_geom_gist.geom column type is geometry(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geometry[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.jsonb_geom_gist'::regclass AND a.attname = 'geom')),
            ('O-1d-type:flat_geog', 'flat_geog.geog column type is geography(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geography[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.flat_geog'::regclass AND a.attname = 'geog')),
            ('O-1d-type:flat_geog_gist', 'flat_geog_gist.geog column type is geography(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geography[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.flat_geog_gist'::regclass AND a.attname = 'geog')),
            ('O-1d-type:flat_geog_spgist', 'flat_geog_spgist.geog column type is geography(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geography[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.flat_geog_spgist'::regclass AND a.attname = 'geog')),
            ('O-1d-type:jsonb_geog', 'jsonb_geog.geog column type is geography(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geography[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.jsonb_geog'::regclass AND a.attname = 'geog')),
            ('O-1d-type:jsonb_geog_gist', 'jsonb_geog_gist.geog column type is geography(Point,4326)', 'true', (SELECT (format_type(a.atttypid, a.atttypmod) ~ '^(postgis[.])?geography[(]Point,4326[)]$')::text FROM pg_attribute a WHERE a.attrelid = 'log_regex_gis.jsonb_geog_gist'::regclass AND a.attname = 'geog')),
            ('O-1g:jsonb_geom', 'jsonb_geom.geom is a stored generated column built with ST_MakePoint(longitude, latitude), SRID 4326', 's/true', (SELECT a.attgenerated::text || '/' || (e LIKE '%st_setsrid(%' AND e LIKE '%st_makepoint(%' AND e LIKE '%4326%' AND strpos(e, 'longitude') > 0 AND strpos(e, 'longitude') < strpos(e, 'latitude'))::text FROM pg_attribute a JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum CROSS JOIN LATERAL (SELECT lower(pg_get_expr(d.adbin, d.adrelid)) AS e) x WHERE a.attrelid = 'log_regex_gis.jsonb_geom'::regclass AND a.attname = 'geom')),
            ('O-1g:jsonb_geom_gist', 'jsonb_geom_gist.geom is a stored generated column built with ST_MakePoint(longitude, latitude), SRID 4326', 's/true', (SELECT a.attgenerated::text || '/' || (e LIKE '%st_setsrid(%' AND e LIKE '%st_makepoint(%' AND e LIKE '%4326%' AND strpos(e, 'longitude') > 0 AND strpos(e, 'longitude') < strpos(e, 'latitude'))::text FROM pg_attribute a JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum CROSS JOIN LATERAL (SELECT lower(pg_get_expr(d.adbin, d.adrelid)) AS e) x WHERE a.attrelid = 'log_regex_gis.jsonb_geom_gist'::regclass AND a.attname = 'geom')),
            ('O-1g:jsonb_geog', 'jsonb_geog.geog is a stored generated column built with ST_MakePoint(longitude, latitude), SRID 4326', 's/true', (SELECT a.attgenerated::text || '/' || (e LIKE '%st_setsrid(%' AND e LIKE '%st_makepoint(%' AND e LIKE '%4326%' AND strpos(e, 'longitude') > 0 AND strpos(e, 'longitude') < strpos(e, 'latitude') AND (e LIKE '%geography(%' OR e LIKE '%::postgis.geography%' OR e LIKE '%::geography%'))::text FROM pg_attribute a JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum CROSS JOIN LATERAL (SELECT lower(pg_get_expr(d.adbin, d.adrelid)) AS e) x WHERE a.attrelid = 'log_regex_gis.jsonb_geog'::regclass AND a.attname = 'geog')),
            ('O-1g:jsonb_geog_gist', 'jsonb_geog_gist.geog is a stored generated column built with ST_MakePoint(longitude, latitude), SRID 4326', 's/true', (SELECT a.attgenerated::text || '/' || (e LIKE '%st_setsrid(%' AND e LIKE '%st_makepoint(%' AND e LIKE '%4326%' AND strpos(e, 'longitude') > 0 AND strpos(e, 'longitude') < strpos(e, 'latitude') AND (e LIKE '%geography(%' OR e LIKE '%::postgis.geography%' OR e LIKE '%::geography%'))::text FROM pg_attribute a JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum CROSS JOIN LATERAL (SELECT lower(pg_get_expr(d.adbin, d.adrelid)) AS e) x WHERE a.attrelid = 'log_regex_gis.jsonb_geog_gist'::regclass AND a.attname = 'geog')),
            ('O-7a', 'flat_numeric fingerprint = source access_log_flat fingerprint', 'f562354dbf6c155f3ed0a93da433e79c', (SELECT md5(string_agg(log_id || ':' || coalesce(latitude_degrees::text, 'NULL') || ':' || coalesce(longitude_degrees::text, 'NULL'), chr(10) ORDER BY log_id)) FROM log_regex_gis.flat_numeric)),
            ('O-7b:jsonb_doc', 'jsonb_doc fingerprint = source access_log_jsonb fingerprint', 'fb3bc16318e6a81c7930aed2217986ea', (SELECT md5(string_agg(log_id || ':' || doc::text, chr(10) ORDER BY log_id)) FROM log_regex_gis.jsonb_doc)),
            ('O-7b:jsonb_doc_expr', 'jsonb_doc_expr.doc = jsonb_doc.doc', '5000', (SELECT count(*) FILTER (WHERE t.doc = j.doc)::text FROM log_regex_gis.jsonb_doc_expr t JOIN log_regex_gis.jsonb_doc j ON j.log_id = t.log_id)),
            ('O-7b:jsonb_geom', 'jsonb_geom.doc = jsonb_doc.doc', '5000', (SELECT count(*) FILTER (WHERE t.doc = j.doc)::text FROM log_regex_gis.jsonb_geom t JOIN log_regex_gis.jsonb_doc j ON j.log_id = t.log_id)),
            ('O-7b:jsonb_geom_gist', 'jsonb_geom_gist.doc = jsonb_doc.doc', '5000', (SELECT count(*) FILTER (WHERE t.doc = j.doc)::text FROM log_regex_gis.jsonb_geom_gist t JOIN log_regex_gis.jsonb_doc j ON j.log_id = t.log_id)),
            ('O-7b:jsonb_geog', 'jsonb_geog.doc = jsonb_doc.doc', '5000', (SELECT count(*) FILTER (WHERE t.doc = j.doc)::text FROM log_regex_gis.jsonb_geog t JOIN log_regex_gis.jsonb_doc j ON j.log_id = t.log_id)),
            ('O-7b:jsonb_geog_gist', 'jsonb_geog_gist.doc = jsonb_doc.doc', '5000', (SELECT count(*) FILTER (WHERE t.doc = j.doc)::text FROM log_regex_gis.jsonb_geog_gist t JOIN log_regex_gis.jsonb_doc j ON j.log_id = t.log_id)),
            ('O-7c', 'flat_numeric_btree = flat_numeric (IS NOT DISTINCT FROM on both columns)', '5000', (SELECT count(*) FILTER (WHERE t.latitude_degrees IS NOT DISTINCT FROM f.latitude_degrees AND t.longitude_degrees IS NOT DISTINCT FROM f.longitude_degrees)::text FROM log_regex_gis.flat_numeric_btree t JOIN log_regex_gis.flat_numeric f ON f.log_id = t.log_id))
        ) AS c (id, name, expected, actual)
    LOOP
        IF chk.expected IS NOT DISTINCT FROM chk.actual THEN
            RAISE NOTICE '% PASS  %: %', chk.id, chk.name, chk.actual;
        ELSE
            v_failed := v_failed + 1;
            RAISE WARNING '% FAIL  %: expected %, actual %', chk.id, chk.name, chk.expected, chk.actual;
        END IF;
    END LOOP;
    PERFORM set_config('step7b.gate46', v_failed::text, false);
END
$gate$;
DO $verdict$
BEGIN
    IF current_setting('step7b.gate46')::integer > 0 THEN
        RAISE EXCEPTION 'sql/46 setup gate FAILED: % of 103 checks', current_setting('step7b.gate46') USING ERRCODE = 'LR020';
    END IF;
    RAISE NOTICE 'sql/46 setup gate PASSED: all 103 checks';
END
$verdict$;

COMMIT;

VACUUM (ANALYZE) log_regex_gis.flat_numeric;
VACUUM (ANALYZE) log_regex_gis.flat_numeric_btree;
VACUUM (ANALYZE) log_regex_gis.flat_geom;
VACUUM (ANALYZE) log_regex_gis.flat_geom_gist;
VACUUM (ANALYZE) log_regex_gis.flat_geom_spgist;
VACUUM (ANALYZE) log_regex_gis.flat_geom_brin;
VACUUM (ANALYZE) log_regex_gis.flat_geog;
VACUUM (ANALYZE) log_regex_gis.flat_geog_gist;
VACUUM (ANALYZE) log_regex_gis.flat_geog_spgist;
VACUUM (ANALYZE) log_regex_gis.jsonb_doc;
VACUUM (ANALYZE) log_regex_gis.jsonb_doc_expr;
VACUUM (ANALYZE) log_regex_gis.jsonb_geom;
VACUUM (ANALYZE) log_regex_gis.jsonb_geom_gist;
VACUUM (ANALYZE) log_regex_gis.jsonb_geog;
VACUUM (ANALYZE) log_regex_gis.jsonb_geog_gist;
