-- =============================================================================
-- Step 7B / 48 - Step 7C spatial index builds (generated in 7B, NOT run in 7B)
-- =============================================================================
-- GENERATED by scripts/step7_postgis_experiment.py - do not edit by hand. Run by sql/run_step7b_postgis_setup.ps1.
-- Plan: docs/Step7B_PostGIS_Setup_Preflight.md (approved).
-- Refuses unless run with -v approved_step=7C (LR022). Exactly the 10 index statements of the Step 7B plan section 5.
-- =============================================================================

\set ON_ERROR_STOP on
\if :{?approved_step}
SELECT :'approved_step' = '7C' AS approved \gset
\else
\set approved false
\endif
\if :approved
\else
DO $refuse$ BEGIN RAISE EXCEPTION 'sql/48 is a Step 7C script; run it only after Step 7C approval with -v approved_step=7C' USING ERRCODE = 'LR022'; END $refuse$;
\endif

CREATE INDEX flat_numeric_btree_lat_lon_idx ON log_regex_gis.flat_numeric_btree USING btree (latitude_degrees, longitude_degrees);
CREATE INDEX flat_geom_gist_idx ON log_regex_gis.flat_geom_gist USING gist (geom postgis.gist_geometry_ops_2d);
CREATE INDEX flat_geom_spgist_idx ON log_regex_gis.flat_geom_spgist USING spgist (geom postgis.spgist_geometry_ops_2d);
CREATE INDEX flat_geom_brin_idx ON log_regex_gis.flat_geom_brin USING brin (geom postgis.brin_geometry_inclusion_ops_2d);
CREATE INDEX flat_geog_gist_idx ON log_regex_gis.flat_geog_gist USING gist (geog postgis.gist_geography_ops);
CREATE INDEX flat_geog_spgist_idx ON log_regex_gis.flat_geog_spgist USING spgist (geog postgis.spgist_geography_ops_nd);
CREATE INDEX jsonb_doc_expr_geom_gist_idx ON log_regex_gis.jsonb_doc_expr USING gist ((postgis.ST_SetSRID(postgis.ST_MakePoint((doc->'fields'->'longitude'->>'degrees')::float8, (doc->'fields'->'latitude'->>'degrees')::float8), 4326)) postgis.gist_geometry_ops_2d);
CREATE INDEX jsonb_doc_expr_geog_gist_idx ON log_regex_gis.jsonb_doc_expr USING gist ((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((doc->'fields'->'longitude'->>'degrees')::float8, (doc->'fields'->'latitude'->>'degrees')::float8), 4326))) postgis.gist_geography_ops);
CREATE INDEX jsonb_geom_gist_idx ON log_regex_gis.jsonb_geom_gist USING gist (geom postgis.gist_geometry_ops_2d);
CREATE INDEX jsonb_geog_gist_idx ON log_regex_gis.jsonb_geog_gist USING gist (geog postgis.gist_geography_ops);
