-- =============================================================================
-- Step 7C / 49 - Build the 10 approved spatial indexes, 3 timed builds each
-- =============================================================================
-- GENERATED by scripts/step7c_spatial_index_experiment.py - do not edit by hand. Run by sql/run_step7c_spatial_indexes.ps1.
-- Design: docs/Step7C_Spatial_Index_Experiment_Design.md (approved).
-- Refuses without -v approved_step=7C (LR023). Each build: DO block with clock_timestamp and WAL insert-LSN difference;
-- builds 1 and 2 are dropped, build 3 is kept. Statements are byte-identical to sql/48. ANALYZE of all 15 tables at the end.
-- =============================================================================

\set ON_ERROR_STOP on
\if :{?approved_step}
SELECT :'approved_step' = '7C' AS approved \gset
\else
\set approved false
\endif
\if :approved
\else
DO $refuse$ BEGIN RAISE EXCEPTION 'sql/49 is the Step 7C build; run it only with -v approved_step=7C' USING ERRCODE = 'LR023'; END $refuse$;
\endif
DO $guard$
BEGIN
    IF (SELECT extversion FROM pg_extension WHERE extname = 'postgis') IS DISTINCT FROM '3.6.2'
       OR (SELECT count(*) FROM pg_class WHERE relnamespace = 'log_regex_gis'::regnamespace AND relkind = 'r') <> 15
       OR (SELECT count(*) FROM pg_index i JOIN pg_class c ON c.oid = i.indrelid WHERE c.relnamespace = 'log_regex_gis'::regnamespace AND NOT i.indisprimary) <> 0 THEN
        RAISE EXCEPTION 'sql/49 refused: not in the verified Step 7B state (postgis 3.6.2, 15 tables, no secondary index)' USING ERRCODE = 'LR023';
    END IF;
END
$guard$;
SET maintenance_work_mem = '64MB';
SET max_parallel_maintenance_workers = 0;
DO $size$
DECLARE
    r record;
BEGIN
    FOR r IN SELECT c.relname, pg_relation_size(c.oid) AS heap, pg_table_size(c.oid) AS tbl, pg_indexes_size(c.oid) AS idx,
                    pg_total_relation_size(c.oid) AS total, c.relpages, c.reltuples
             FROM pg_class c WHERE c.relnamespace = 'log_regex_gis'::regnamespace AND c.relkind = 'r' ORDER BY c.relname LOOP
        RAISE NOTICE '@@TABLESIZE phase=before table=% heap=% table_size=% indexes=% total=% relpages=% reltuples=%',
            r.relname, r.heap, r.tbl, r.idx, r.total, r.relpages, r.reltuples;
    END LOOP;
    FOR r IN SELECT ic.relname AS idx, c.relname AS tbl, am.amname, pg_relation_size(ic.oid) AS bytes, ic.relpages, ic.reltuples,
                    coalesce(array_to_string(ic.reloptions, ','), '') AS opts
             FROM pg_index i JOIN pg_class ic ON ic.oid = i.indexrelid JOIN pg_class c ON c.oid = i.indrelid JOIN pg_am am ON am.oid = ic.relam
             WHERE c.relnamespace = 'log_regex_gis'::regnamespace AND NOT i.indisprimary ORDER BY ic.relname LOOP
        RAISE NOTICE '@@INDEXSIZE phase=before index=% table=% method=% bytes=% relpages=% reltuples=% options=%',
            r.idx, r.tbl, r.amname, r.bytes, r.relpages, r.reltuples, r.opts;
    END LOOP;
END
$size$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_numeric_btree_lat_lon_idx ON log_regex_gis.flat_numeric_btree USING btree (latitude_degrees, longitude_degrees)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=N-1 index=flat_numeric_btree_lat_lon_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_numeric_btree_lat_lon_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_numeric_btree_lat_lon_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_numeric_btree_lat_lon_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_numeric_btree_lat_lon_idx ON log_regex_gis.flat_numeric_btree USING btree (latitude_degrees, longitude_degrees)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=N-1 index=flat_numeric_btree_lat_lon_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_numeric_btree_lat_lon_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_numeric_btree_lat_lon_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_numeric_btree_lat_lon_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_numeric_btree_lat_lon_idx ON log_regex_gis.flat_numeric_btree USING btree (latitude_degrees, longitude_degrees)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=N-1 index=flat_numeric_btree_lat_lon_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_numeric_btree_lat_lon_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_numeric_btree_lat_lon_idx'));
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geom_gist_idx ON log_regex_gis.flat_geom_gist USING gist (geom postgis.gist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=G-1 index=flat_geom_gist_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geom_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geom_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geom_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geom_gist_idx ON log_regex_gis.flat_geom_gist USING gist (geom postgis.gist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=G-1 index=flat_geom_gist_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geom_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geom_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geom_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geom_gist_idx ON log_regex_gis.flat_geom_gist USING gist (geom postgis.gist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=G-1 index=flat_geom_gist_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geom_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geom_gist_idx'));
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geom_spgist_idx ON log_regex_gis.flat_geom_spgist USING spgist (geom postgis.spgist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=G-2 index=flat_geom_spgist_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geom_spgist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geom_spgist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geom_spgist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geom_spgist_idx ON log_regex_gis.flat_geom_spgist USING spgist (geom postgis.spgist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=G-2 index=flat_geom_spgist_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geom_spgist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geom_spgist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geom_spgist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geom_spgist_idx ON log_regex_gis.flat_geom_spgist USING spgist (geom postgis.spgist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=G-2 index=flat_geom_spgist_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geom_spgist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geom_spgist_idx'));
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geom_brin_idx ON log_regex_gis.flat_geom_brin USING brin (geom postgis.brin_geometry_inclusion_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=G-3 index=flat_geom_brin_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geom_brin_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geom_brin_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geom_brin_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geom_brin_idx ON log_regex_gis.flat_geom_brin USING brin (geom postgis.brin_geometry_inclusion_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=G-3 index=flat_geom_brin_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geom_brin_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geom_brin_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geom_brin_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geom_brin_idx ON log_regex_gis.flat_geom_brin USING brin (geom postgis.brin_geometry_inclusion_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=G-3 index=flat_geom_brin_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geom_brin_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geom_brin_idx'));
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geog_gist_idx ON log_regex_gis.flat_geog_gist USING gist (geog postgis.gist_geography_ops)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=Y-1 index=flat_geog_gist_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geog_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geog_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geog_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geog_gist_idx ON log_regex_gis.flat_geog_gist USING gist (geog postgis.gist_geography_ops)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=Y-1 index=flat_geog_gist_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geog_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geog_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geog_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geog_gist_idx ON log_regex_gis.flat_geog_gist USING gist (geog postgis.gist_geography_ops)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=Y-1 index=flat_geog_gist_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geog_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geog_gist_idx'));
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geog_spgist_idx ON log_regex_gis.flat_geog_spgist USING spgist (geog postgis.spgist_geography_ops_nd)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=Y-2 index=flat_geog_spgist_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geog_spgist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geog_spgist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geog_spgist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geog_spgist_idx ON log_regex_gis.flat_geog_spgist USING spgist (geog postgis.spgist_geography_ops_nd)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=Y-2 index=flat_geog_spgist_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geog_spgist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geog_spgist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.flat_geog_spgist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX flat_geog_spgist_idx ON log_regex_gis.flat_geog_spgist USING spgist (geog postgis.spgist_geography_ops_nd)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=Y-2 index=flat_geog_spgist_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.flat_geog_spgist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.flat_geog_spgist_idx'));
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_doc_expr_geom_gist_idx ON log_regex_gis.jsonb_doc_expr USING gist ((postgis.ST_SetSRID(postgis.ST_MakePoint((doc->''fields''->''longitude''->>''degrees'')::float8, (doc->''fields''->''latitude''->>''degrees'')::float8), 4326)) postgis.gist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-1 index=jsonb_doc_expr_geom_gist_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_doc_expr_geom_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_doc_expr_geom_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.jsonb_doc_expr_geom_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_doc_expr_geom_gist_idx ON log_regex_gis.jsonb_doc_expr USING gist ((postgis.ST_SetSRID(postgis.ST_MakePoint((doc->''fields''->''longitude''->>''degrees'')::float8, (doc->''fields''->''latitude''->>''degrees'')::float8), 4326)) postgis.gist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-1 index=jsonb_doc_expr_geom_gist_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_doc_expr_geom_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_doc_expr_geom_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.jsonb_doc_expr_geom_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_doc_expr_geom_gist_idx ON log_regex_gis.jsonb_doc_expr USING gist ((postgis.ST_SetSRID(postgis.ST_MakePoint((doc->''fields''->''longitude''->>''degrees'')::float8, (doc->''fields''->''latitude''->>''degrees'')::float8), 4326)) postgis.gist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-1 index=jsonb_doc_expr_geom_gist_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_doc_expr_geom_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_doc_expr_geom_gist_idx'));
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_doc_expr_geog_gist_idx ON log_regex_gis.jsonb_doc_expr USING gist ((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((doc->''fields''->''longitude''->>''degrees'')::float8, (doc->''fields''->''latitude''->>''degrees'')::float8), 4326))) postgis.gist_geography_ops)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-2 index=jsonb_doc_expr_geog_gist_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_doc_expr_geog_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_doc_expr_geog_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.jsonb_doc_expr_geog_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_doc_expr_geog_gist_idx ON log_regex_gis.jsonb_doc_expr USING gist ((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((doc->''fields''->''longitude''->>''degrees'')::float8, (doc->''fields''->''latitude''->>''degrees'')::float8), 4326))) postgis.gist_geography_ops)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-2 index=jsonb_doc_expr_geog_gist_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_doc_expr_geog_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_doc_expr_geog_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.jsonb_doc_expr_geog_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_doc_expr_geog_gist_idx ON log_regex_gis.jsonb_doc_expr USING gist ((postgis.geography(postgis.ST_SetSRID(postgis.ST_MakePoint((doc->''fields''->''longitude''->>''degrees'')::float8, (doc->''fields''->''latitude''->>''degrees'')::float8), 4326))) postgis.gist_geography_ops)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-2 index=jsonb_doc_expr_geog_gist_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_doc_expr_geog_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_doc_expr_geog_gist_idx'));
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_geom_gist_idx ON log_regex_gis.jsonb_geom_gist USING gist (geom postgis.gist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-3 index=jsonb_geom_gist_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_geom_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_geom_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.jsonb_geom_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_geom_gist_idx ON log_regex_gis.jsonb_geom_gist USING gist (geom postgis.gist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-3 index=jsonb_geom_gist_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_geom_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_geom_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.jsonb_geom_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_geom_gist_idx ON log_regex_gis.jsonb_geom_gist USING gist (geom postgis.gist_geometry_ops_2d)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-3 index=jsonb_geom_gist_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_geom_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_geom_gist_idx'));
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_geog_gist_idx ON log_regex_gis.jsonb_geog_gist USING gist (geog postgis.gist_geography_ops)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-4 index=jsonb_geog_gist_idx build=1 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_geog_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_geog_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.jsonb_geog_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_geog_gist_idx ON log_regex_gis.jsonb_geog_gist USING gist (geog postgis.gist_geography_ops)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-4 index=jsonb_geog_gist_idx build=2 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_geog_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_geog_gist_idx'));
    EXECUTE 'DROP INDEX log_regex_gis.jsonb_geog_gist_idx';
END
$build$;
DO $build$
DECLARE
    v_t0  timestamptz;
    v_l0  pg_lsn;
    v_ms  numeric;
    v_wal numeric;
BEGIN
    v_l0 := pg_current_wal_insert_lsn();
    v_t0 := clock_timestamp();
    EXECUTE 'CREATE INDEX jsonb_geog_gist_idx ON log_regex_gis.jsonb_geog_gist USING gist (geog postgis.gist_geography_ops)';
    v_ms := extract(epoch FROM clock_timestamp() - v_t0) * 1000;
    v_wal := pg_wal_lsn_diff(pg_current_wal_insert_lsn(), v_l0);
    RAISE NOTICE '@@BUILD id=J-4 index=jsonb_geog_gist_idx build=3 ms=% wal=% bytes=% relpages=%', round(v_ms, 3), v_wal,
        pg_relation_size(to_regclass('log_regex_gis.jsonb_geog_gist_idx')), (SELECT relpages FROM pg_class WHERE oid = to_regclass('log_regex_gis.jsonb_geog_gist_idx'));
END
$build$;
ANALYZE log_regex_gis.flat_numeric;
ANALYZE log_regex_gis.flat_numeric_btree;
ANALYZE log_regex_gis.flat_geom;
ANALYZE log_regex_gis.flat_geom_gist;
ANALYZE log_regex_gis.flat_geom_spgist;
ANALYZE log_regex_gis.flat_geom_brin;
ANALYZE log_regex_gis.flat_geog;
ANALYZE log_regex_gis.flat_geog_gist;
ANALYZE log_regex_gis.flat_geog_spgist;
ANALYZE log_regex_gis.jsonb_doc;
ANALYZE log_regex_gis.jsonb_doc_expr;
ANALYZE log_regex_gis.jsonb_geom;
ANALYZE log_regex_gis.jsonb_geom_gist;
ANALYZE log_regex_gis.jsonb_geog;
ANALYZE log_regex_gis.jsonb_geog_gist;
DO $size$
DECLARE
    r record;
BEGIN
    FOR r IN SELECT c.relname, pg_relation_size(c.oid) AS heap, pg_table_size(c.oid) AS tbl, pg_indexes_size(c.oid) AS idx,
                    pg_total_relation_size(c.oid) AS total, c.relpages, c.reltuples
             FROM pg_class c WHERE c.relnamespace = 'log_regex_gis'::regnamespace AND c.relkind = 'r' ORDER BY c.relname LOOP
        RAISE NOTICE '@@TABLESIZE phase=after table=% heap=% table_size=% indexes=% total=% relpages=% reltuples=%',
            r.relname, r.heap, r.tbl, r.idx, r.total, r.relpages, r.reltuples;
    END LOOP;
    FOR r IN SELECT ic.relname AS idx, c.relname AS tbl, am.amname, pg_relation_size(ic.oid) AS bytes, ic.relpages, ic.reltuples,
                    coalesce(array_to_string(ic.reloptions, ','), '') AS opts
             FROM pg_index i JOIN pg_class ic ON ic.oid = i.indexrelid JOIN pg_class c ON c.oid = i.indrelid JOIN pg_am am ON am.oid = ic.relam
             WHERE c.relnamespace = 'log_regex_gis'::regnamespace AND NOT i.indisprimary ORDER BY ic.relname LOOP
        RAISE NOTICE '@@INDEXSIZE phase=after index=% table=% method=% bytes=% relpages=% reltuples=% options=%',
            r.idx, r.tbl, r.amname, r.bytes, r.relpages, r.reltuples, r.opts;
    END LOOP;
END
$size$;
