-- =============================================================================
-- Step 7C / 52 - Cleanup: drop the 10 Step 7C indexes (back to the Step 7B state)
-- =============================================================================
-- GENERATED by scripts/step7c_spatial_index_experiment.py - do not edit by hand. Run by sql/run_step7c_spatial_indexes.ps1.
-- Design: docs/Step7C_Spatial_Index_Experiment_Design.md (approved).
-- Run only on request or after a failed build, with -v confirm_cleanup=yes (LR026). Drops exactly the 10 designed names.
-- =============================================================================

\set ON_ERROR_STOP on
\if :{?confirm_cleanup}
SELECT :'confirm_cleanup' = 'yes' AS approved \gset
\else
\set approved false
\endif
\if :approved
\else
DO $refuse$ BEGIN RAISE EXCEPTION 'sql/52 drops the Step 7C indexes; run it only with -v confirm_cleanup=yes' USING ERRCODE = 'LR026'; END $refuse$;
\endif
DROP INDEX IF EXISTS log_regex_gis.flat_numeric_btree_lat_lon_idx;
DROP INDEX IF EXISTS log_regex_gis.flat_geom_gist_idx;
DROP INDEX IF EXISTS log_regex_gis.flat_geom_spgist_idx;
DROP INDEX IF EXISTS log_regex_gis.flat_geom_brin_idx;
DROP INDEX IF EXISTS log_regex_gis.flat_geog_gist_idx;
DROP INDEX IF EXISTS log_regex_gis.flat_geog_spgist_idx;
DROP INDEX IF EXISTS log_regex_gis.jsonb_doc_expr_geom_gist_idx;
DROP INDEX IF EXISTS log_regex_gis.jsonb_doc_expr_geog_gist_idx;
DROP INDEX IF EXISTS log_regex_gis.jsonb_geom_gist_idx;
DROP INDEX IF EXISTS log_regex_gis.jsonb_geog_gist_idx;
ANALYZE log_regex_gis.flat_geog_gist;
ANALYZE log_regex_gis.flat_geog_spgist;
ANALYZE log_regex_gis.flat_geom_brin;
ANALYZE log_regex_gis.flat_geom_gist;
ANALYZE log_regex_gis.flat_geom_spgist;
ANALYZE log_regex_gis.flat_numeric_btree;
ANALYZE log_regex_gis.jsonb_doc_expr;
ANALYZE log_regex_gis.jsonb_geog_gist;
ANALYZE log_regex_gis.jsonb_geom_gist;
