"""
Loads one micro-batch file into Snowflake and writes the audit logs.

Steps for every batch (``SnowflakeLoader.load_batch``):

    1. PUT      upload the local NDJSON file to the internal stage;
    2. COPY     load it into the target table with MATCH_BY_COLUMN_NAME;
    3. detect   if the batch carried field names the table did not have,
                re-read the table's columns to see what Snowflake added;
    4. audit    write one INGEST_BATCH_LOG row and one SCHEMA_EVOLUTION_LOG
                row per new column.

SCHEMA EVOLUTION IS DONE BY SNOWFLAKE, NOT BY THIS CODE. The target table has
ENABLE_SCHEMA_EVOLUTION = TRUE, so COPY INTO itself adds a column for any
top-level field without one. This module never issues ALTER TABLE. Step 3 only
observes the result, and SCHEMA_EVOLUTION_LOG is an application-level audit
table. If writing the audit rows fails, the data is still loaded and the
column still exists; the failure is logged and the pipeline continues.

BATCH SPLITTING. Snowflake lets one COPY add at most
``MAX_NEW_COLUMNS_PER_COPY`` new columns (100, measured on this account); a
COPY that would add more fails as a whole. A batch that introduces more new
fields than that is therefore split, in record order, into several part files
that each stay within the limit, and steps 1 to 4 run once per part. The
batch counts as loaded only when EVERY part is loaded; until then
``load_batch`` raises and the consumer commits nothing to Kafka.
"""

from __future__ import annotations

import json
import logging
import re
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

import snowflake.connector

from config import settings
from consumer.transform import META_OFFSET, META_PARTITION

logger = logging.getLogger("consumer.snowflake_loader")

# Batch file names are generated by BatchBuffer.file_name. The name is placed
# into SQL text (PUT and COPY cannot take it as a bind variable), so it is
# checked against this strict pattern first.
_SAFE_FILE_NAME = re.compile(r"^[A-Za-z0-9._-]+$")

# Status text Snowflake returns when COPY found nothing new to load, which
# happens when the named file was already loaded by an earlier COPY.
_NOTHING_LOADED_MARKER = "0 files processed"


class BatchNotLoadedError(RuntimeError):
    """Raised when COPY INTO ran but did not read the batch file at all.

    Snowflake reports a file-level failure (for example "Remote file ... was
    not found") as an ordinary result row with status LOAD_FAILED, not as an
    SQL error. Without this exception the consumer would take that for a
    finished batch and commit the Kafka offsets, losing the messages.
    """


class RecordTooWideError(ValueError):
    """Raised when ONE record introduces more new columns than a COPY may add.

    Splitting cannot help here: a record is one row and must be loaded by one
    COPY. The consumer prevents this case by sending such a message to the
    dead-letter topic before it is buffered; this error is the safety net.
    """


def plan_splits(record_columns: list[set[str]], known_columns: set[str], limit: int) -> list[tuple[int, int]]:
    """Decide how to cut a batch so that no part adds more than ``limit`` columns.

    The records are walked in their original order. Records are added to the
    current part until the next one would push the number of NEW columns in
    that part past the limit; then the part is closed and a new one starts.
    Columns introduced by a closed part exist in the table by the time the
    next part is loaded, so they no longer count as new.

    This function is pure (no I/O), so it can be unit tested directly.

    Args:
        record_columns: For each record, in order, the set of its column names.
        known_columns: Columns the table already has.
        limit: Most new columns one COPY may add.

    Returns:
        ``(start, end)`` index pairs, ``end`` exclusive, covering every record
        exactly once and in order. A batch that needs no splitting gives one pair.

    Raises:
        RecordTooWideError: if a single record alone exceeds the limit.
    """
    ranges: list[tuple[int, int]] = []
    # Columns that exist, or will exist once the already closed parts are loaded.
    existing = set(known_columns)
    # New columns the part currently being filled would add.
    pending: set[str] = set()
    start = 0
    for index, columns in enumerate(record_columns):
        new_here = columns - existing
        if len(new_here) > limit:
            raise RecordTooWideError(
                f"Record {index} introduces {len(new_here)} new columns; one COPY can add at most {limit}"
            )
        if len(pending | new_here) > limit:
            # Close the current part before this record.
            ranges.append((start, index))
            existing |= pending
            pending = set()
            start = index
            # Some of this record's fields were introduced by the part just closed.
            new_here = columns - existing
        pending |= new_here
    ranges.append((start, len(record_columns)))
    return ranges


@dataclass
class BatchInfo:
    """What the loader needs to know about a batch, besides the file itself."""

    topic: str
    record_count: int
    # Every column name appearing in the batch's records.
    column_names: set[str]
    # Column name -> (partition, offset) of the first record that carried it.
    first_seen: dict[str, tuple[int, int]]
    # JSON text describing first/last offset per partition, for the audit log.
    offset_ranges_text: str


@dataclass
class LoadResult:
    """Outcome of loading one batch, as reported by Snowflake."""

    batch_id: str
    file_name: str
    # LOADED, PARTIALLY_LOADED, LOAD_FAILED, or ALREADY_LOADED (see load_batch).
    status: str
    rows_parsed: int = 0
    rows_loaded: int = 0
    errors_seen: int = 0
    first_error: str | None = None
    query_id: str | None = None
    # (column name, data type) for every column Snowflake added in this load.
    new_columns: list[tuple[str, str]] = field(default_factory=list)
    load_seconds: float = 0.0
    # Number of COPY operations the batch needed (more than 1 = it was split).
    copies: int = 1


@dataclass
class _Part:
    """One COPY's worth of a batch: a file, its facts, and how far it got."""

    file_path: Path
    info: BatchInfo
    # Table columns before this part's first attempt; kept across retries so
    # that columns added by an attempt that failed afterwards are still noticed.
    columns_before: dict[str, str] | None = None
    # True once a COPY for this part may have reached Snowflake.
    attempted: bool = False
    # Set when the part is loaded; a loaded part is never loaded again.
    result: LoadResult | None = None


@dataclass
class _Plan:
    """How one batch is being loaded. Remembered across retries of that batch."""

    base_name: str
    batch_id: str
    parts: list[_Part]

    @property
    def is_split(self) -> bool:
        """True when the batch needed more than one COPY."""
        return len(self.parts) > 1


class SnowflakeLoader:
    """Owns the Snowflake connection and performs the load of each batch."""

    def __init__(
        self,
        table: str | None = None,
        connection_factory: Callable[[], Any] | None = None,
    ) -> None:
        """Prepare the loader. No connection is opened until it is needed.

        Args:
            table: Target table name. Defaults to ``SNOWFLAKE_TABLE``. The
                end-to-end tests pass a separate test table here.
            connection_factory: Function returning an open Snowflake
                connection. Defaults to a real connection built from the
                settings; unit tests pass a fake.
        """
        self.table = settings.validate_identifier(table or settings.SNOWFLAKE_TABLE, "table")
        self._connection_factory = connection_factory or self._open_connection
        self._connection: Any = None
        # Column name -> data type, as last read from Snowflake. None means
        # "not read yet" (or "must be re-read after a reconnect").
        self._known_columns: dict[str, str] | None = None
        # Plan of the batch currently being loaded (None between batches).
        self._plan: _Plan | None = None

    # ------------------------------------------------------------------
    # Connection handling
    # ------------------------------------------------------------------

    @staticmethod
    def _open_connection() -> Any:
        """Open a Snowflake connection using the named config.toml connection.

        The login details come from the Snowflake config file, so no account,
        user or password appears in this project. Role, warehouse, database
        and schema are set explicitly so the pipeline does not depend on the
        defaults stored with that connection.
        """
        return snowflake.connector.connect(
            connection_name=settings.require_snowflake_connection_name(),
            role=settings.SNOWFLAKE_ROLE,
            warehouse=settings.SNOWFLAKE_WAREHOUSE,
            database=settings.SNOWFLAKE_DATABASE,
            schema=settings.SNOWFLAKE_SCHEMA,
            # Keeps the session from expiring while the consumer waits on a
            # quiet topic for hours. This is a lightweight heartbeat to the
            # service; it runs no query and does not resume the warehouse.
            client_session_keep_alive=True,
            # Tag every query so the pipeline's activity is easy to find in
            # Snowflake query history.
            session_parameters={"QUERY_TAG": settings.SNOWFLAKE_QUERY_TAG},
        )

    def _cursor(self) -> Any:
        """Return a cursor, opening the connection first if necessary."""
        if self._connection is None or self._connection.is_closed():
            logger.info("Connecting to Snowflake ...")
            self._connection = self._connection_factory()
            # The table may have changed while we were disconnected.
            self._known_columns = None
        return self._connection.cursor()

    def reset_connection(self) -> None:
        """Drop the current connection so the next call opens a fresh one.

        Called after any Snowflake error: the cheapest reliable way to recover
        from a broken network link or an expired session is to reconnect.
        """
        if self._connection is not None:
            try:
                self._connection.close()
            except Exception:  # noqa: BLE001 - closing a broken connection may itself fail
                logger.debug("Ignoring error while closing a broken connection", exc_info=True)
        self._connection = None
        self._known_columns = None

    def close(self) -> None:
        """Close the connection at shutdown and remove leftover part files."""
        self._drop_plan()
        self.reset_connection()

    # ------------------------------------------------------------------
    # Table columns
    # ------------------------------------------------------------------

    def describe_columns(self) -> dict[str, str]:
        """Read the target table's current columns from Snowflake.

        DESCRIBE TABLE is a metadata command: it needs no running warehouse,
        so checking for new columns costs nothing.

        Returns:
            Column name -> data type, for example ``{"QUANTITY": "NUMBER(38,0)"}``.
        """
        cursor = self._cursor()
        try:
            cursor.execute(f"DESCRIBE TABLE {self.table}")
            # First two result columns are "name" and "type".
            return {row[0]: row[1] for row in cursor.fetchall()}
        finally:
            cursor.close()

    def known_columns(self) -> dict[str, str]:
        """Return the cached column list, reading it from Snowflake if needed."""
        if self._known_columns is None:
            self._known_columns = self.describe_columns()
            logger.info("Table %s currently has %d columns.", self.table, len(self._known_columns))
        return self._known_columns

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    def load_batch(self, file_path: Path, info: BatchInfo, is_retry: bool = False) -> LoadResult:
        """Upload one batch file and load it into the target table.

        Normally this is one PUT and one COPY. If the batch introduces more
        new columns than one COPY may add, it is split into parts and each
        part is loaded in turn (see ``plan_splits``).

        The batch is loaded only when this method RETURNS. If any part fails,
        it raises; the consumer then commits nothing and calls again with the
        same file. Parts that were already loaded are remembered and skipped
        on that next call, so a retry does not load them a second time.

        Args:
            file_path: Local NDJSON file written by ``BatchBuffer.write_file``.
            info: Facts about the batch needed for the audit logs.
            is_retry: True when this same file is being loaded again after an
                earlier attempt raised a Snowflake error.

        Returns:
            What Snowflake reported, summed over all parts if the batch was split.

        Raises:
            snowflake.connector.Error: on any Snowflake failure. The caller
                keeps the batch and tries again; nothing is committed to Kafka.
            BatchNotLoadedError: if COPY read no rows from a file that
                contains records. Nothing is committed to Kafka.
            RecordTooWideError: if one record alone exceeds the column limit.
            RuntimeError: if COPY loaded nothing on a first attempt.
        """
        if not _SAFE_FILE_NAME.match(file_path.name):
            raise ValueError(f"Unsafe batch file name: {file_path.name!r}")

        plan = self._plan_for(file_path, info)
        for part in plan.parts:
            if part.result is not None:
                # Loaded by an earlier attempt of this same batch: skip it.
                continue
            # "COPY may already have run" applies only to a part that was
            # actually sent to Snowflake before; later parts are first attempts.
            part_is_retry = is_retry and part.attempted
            part.result = self._load_part(plan.batch_id, part, part_is_retry)

        result = self._combine(plan)
        self._drop_plan()
        return result

    # ------------------------------------------------------------------
    # Planning: one COPY, or several parts
    # ------------------------------------------------------------------

    def _plan_for(self, file_path: Path, info: BatchInfo) -> _Plan:
        """Return the plan for this batch, creating it on the first attempt.

        The plan is keyed by the batch file name. The consumer reuses that
        name on every retry, so a retry gets the SAME plan back: the same
        parts, the same part file names, and the record of which parts are
        already loaded. Re-planning on a retry would cut the batch differently
        (columns added by the loaded parts would no longer count as new) and
        load some rows twice.
        """
        if self._plan is not None and self._plan.base_name == file_path.name:
            return self._plan
        # A different batch: forget any plan left over from an abandoned one.
        self._drop_plan()

        limit = settings.MAX_NEW_COLUMNS_PER_COPY
        known = set(self.known_columns())
        if len(info.column_names - known) <= limit:
            # The normal case: the whole file in one COPY.
            parts = [_Part(file_path=file_path, info=info)]
        else:
            parts = self._split_file(file_path, info, known, limit)
            logger.warning(
                "Batch %s introduces %d new columns (limit %d per COPY): split into %d parts.",
                file_path.name, len(info.column_names - known), limit, len(parts),
            )
        self._plan = _Plan(base_name=file_path.name, batch_id=str(uuid.uuid4()), parts=parts)
        return self._plan

    @staticmethod
    def _split_file(file_path: Path, info: BatchInfo, known: set[str], limit: int) -> list[_Part]:
        """Cut the batch file into part files that each stay within the limit.

        Every line of the original file goes into exactly one part, in the
        original order, byte for byte. Nothing is dropped or duplicated.
        """
        lines = file_path.read_text(encoding="utf-8").splitlines()
        records = [json.loads(line) for line in lines]
        ranges = plan_splits([set(record) for record in records], known, limit)

        parts: list[_Part] = []
        for number, (start, end) in enumerate(ranges, start=1):
            part_records = records[start:end]
            # Example: order_events_p0-0_o0-9_3f9a1c2e_part01of03.json
            part_path = file_path.with_name(f"{file_path.stem}_part{number:02d}of{len(ranges):02d}.json")
            part_path.write_text("".join(line + "\n" for line in lines[start:end]), encoding="utf-8", newline="\n")

            column_names: set[str] = set()
            # partition -> [first offset, last offset] within this part.
            offsets: dict[int, list[int]] = {}
            for record in part_records:
                column_names.update(record)
                partition, offset = record.get(META_PARTITION), record.get(META_OFFSET)
                if partition is not None and offset is not None:
                    bounds = offsets.setdefault(partition, [offset, offset])
                    bounds[0], bounds[1] = min(bounds[0], offset), max(bounds[1], offset)

            parts.append(
                _Part(
                    file_path=part_path,
                    info=BatchInfo(
                        topic=info.topic,
                        record_count=len(part_records),
                        column_names=column_names,
                        first_seen={name: info.first_seen[name] for name in column_names if name in info.first_seen},
                        offset_ranges_text=json.dumps({str(key): value for key, value in sorted(offsets.items())}),
                    ),
                )
            )
        return parts

    def _drop_plan(self) -> None:
        """Forget the current plan and delete the part files it created.

        The original batch file belongs to the consumer and is not touched.
        """
        if self._plan is not None and self._plan.is_split:
            for part in self._plan.parts:
                part.file_path.unlink(missing_ok=True)
        self._plan = None

    @staticmethod
    def _combine(plan: _Plan) -> LoadResult:
        """Turn the results of all parts into one result for the whole batch."""
        results = [part.result for part in plan.parts if part.result is not None]
        if len(results) == 1:
            return results[0]

        rows_loaded = sum(result.rows_loaded for result in results)
        errors_seen = sum(result.errors_seen for result in results)
        if all(result.status == "ALREADY_LOADED" for result in results):
            status = "ALREADY_LOADED"
        elif errors_seen == 0:
            status = "LOADED"
        elif rows_loaded == 0:
            status = "LOAD_FAILED"
        else:
            status = "PARTIALLY_LOADED"
        return LoadResult(
            batch_id=plan.batch_id,
            file_name=plan.base_name,
            status=status,
            rows_parsed=sum(result.rows_parsed for result in results),
            rows_loaded=rows_loaded,
            errors_seen=errors_seen,
            first_error=next((result.first_error for result in results if result.first_error), None),
            query_id=results[-1].query_id,
            new_columns=[column for result in results for column in result.new_columns],
            load_seconds=round(sum(result.load_seconds for result in results), 3),
            copies=len(results),
        )

    # ------------------------------------------------------------------
    # Loading one part (the whole batch, when it is not split)
    # ------------------------------------------------------------------

    def _load_part(self, batch_id: str, part: _Part, is_retry: bool) -> LoadResult:
        """PUT and COPY one file, check the result, write its audit rows.

        Raises:
            snowflake.connector.Error, BatchNotLoadedError, RuntimeError:
                as described for ``load_batch``. ``part.result`` stays unset,
                so the part is attempted again on the next call.
        """
        file_path = part.file_path
        started = time.monotonic()
        try:
            if part.columns_before is None:
                # Columns the table had BEFORE this part; needed to spot new ones.
                part.columns_before = dict(self.known_columns())
            cursor = self._cursor()
            try:
                self._put(cursor, file_path)
                # From here on the COPY may have reached Snowflake.
                part.attempted = True
                result = self._copy(cursor, file_path.name, batch_id)
                self._ensure_file_was_read(result, part.info)
                self._remove_staged_file(cursor, file_path.name)
            finally:
                cursor.close()
        except snowflake.connector.Error:
            # Reconnect on the next attempt, then let the consumer retry.
            self.reset_connection()
            raise

        if result.status == "ALREADY_LOADED" and not is_retry:
            # On a first attempt the file name is brand new, so "nothing
            # loaded" would mean the data did not reach the table.
            raise RuntimeError(f"COPY loaded nothing from {file_path.name} on the first attempt")

        result.load_seconds = round(time.monotonic() - started, 3)
        result.new_columns = self._detect_new_columns(part.info, part.columns_before)
        self._write_audit_logs(result, part.info)
        return result

    def _put(self, cursor: Any, file_path: Path) -> None:
        """Upload the local file to the internal stage.

        PUT needs no warehouse. ``as_posix`` gives forward slashes, and the
        whole URI is quoted so a space in the path cannot cut the name short.
        AUTO_COMPRESS gzips the file on upload, so the staged name ends in
        ``.gz``. OVERWRITE lets a retry upload the same file again.
        """
        cursor.execute(
            f"PUT 'file://{file_path.as_posix()}' @{settings.SNOWFLAKE_STAGE} "
            "AUTO_COMPRESS = TRUE OVERWRITE = TRUE"
        )
        row = cursor.fetchone()
        # Result columns: source, target, source_size, target_size,
        # source_compression, target_compression, status, message.
        status = row[6] if row else "NO RESULT"
        if status != "UPLOADED":
            raise RuntimeError(f"PUT of {file_path.name} returned status {status!r}")

    def _copy(self, cursor: Any, file_name: str, batch_id: str) -> LoadResult:
        """Run COPY INTO for one staged file and translate the result.

        The options that matter:
            MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
                maps each top-level JSON key to the column of the same name.
                Together with ENABLE_SCHEMA_EVOLUTION on the table, a key
                without a column makes SNOWFLAKE add that column.
            ON_ERROR = CONTINUE
                a row that cannot be loaded (for example text in a NUMBER
                column) is skipped and counted; the other rows still load.
            PURGE = TRUE
                Snowflake deletes the staged file after loading it.
        """
        cursor.execute(
            f"COPY INTO {self.table} "
            f"FROM @{settings.SNOWFLAKE_STAGE} "
            f"FILES = ('{file_name}.gz') "
            f"FILE_FORMAT = (FORMAT_NAME = {settings.SNOWFLAKE_FILE_FORMAT}) "
            "MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE "
            "ON_ERROR = CONTINUE "
            "PURGE = TRUE"
        )
        # Read the result by column NAME rather than position, so a change in
        # column order between Snowflake versions cannot mix the values up.
        names = [column[0].lower() for column in cursor.description]
        row = cursor.fetchone()
        values = dict(zip(names, row)) if row else {}

        if "rows_loaded" not in values:
            # No per-file result: COPY returned only a status message such as
            # "Copy executed with 0 files processed." Snowflake remembers the
            # files it has loaded and skips them, so this is what a repeated
            # COPY of an already loaded file looks like.
            message = str(values.get("status", ""))
            if _NOTHING_LOADED_MARKER in message:
                return LoadResult(batch_id=batch_id, file_name=file_name, status="ALREADY_LOADED", query_id=cursor.sfqid)
            raise RuntimeError(f"Unexpected COPY result for {file_name}: {values}")

        return LoadResult(
            batch_id=batch_id,
            file_name=file_name,
            status=str(values.get("status", "")),
            rows_parsed=int(values.get("rows_parsed") or 0),
            rows_loaded=int(values.get("rows_loaded") or 0),
            errors_seen=int(values.get("errors_seen") or 0),
            first_error=values.get("first_error"),
            query_id=cursor.sfqid,
        )

    @staticmethod
    def _ensure_file_was_read(result: LoadResult, info: BatchInfo) -> None:
        """Fail the batch if COPY did not read any row of a non-empty file.

        ``rows_parsed`` is the number of rows Snowflake read from the file.
        Zero rows parsed for a batch that holds records means the file itself
        was not loaded (not found, unreadable, ...). That is different from
        rows being REJECTED: a rejected row is still parsed and is counted in
        ``errors_seen``, and such a batch is complete and must be committed.

        An ALREADY_LOADED result is left alone here; ``load_batch`` decides
        whether that is acceptable (only on a retry).

        Raises:
            BatchNotLoadedError: so the caller retries and commits nothing.
        """
        if result.status == "ALREADY_LOADED":
            return
        if info.record_count > 0 and result.rows_parsed == 0:
            raise BatchNotLoadedError(
                f"COPY read 0 of {info.record_count} rows from {result.file_name} "
                f"(status {result.status}): {result.first_error}"
            )

    def _remove_staged_file(self, cursor: Any, file_name: str) -> None:
        """Delete the staged file, in case PURGE left it behind.

        PURGE does not report failures, and a file with rejected rows may be
        kept. Removing it explicitly stops files from piling up in the stage.
        REMOVE needs no warehouse. A failure here is harmless, so it is only
        logged.
        """
        try:
            cursor.execute(f"REMOVE @{settings.SNOWFLAKE_STAGE}/{file_name}.gz")
        except snowflake.connector.Error:
            logger.warning("Could not remove staged file %s.gz", file_name, exc_info=True)

    # ------------------------------------------------------------------
    # Observing schema evolution and writing audit rows
    # ------------------------------------------------------------------

    def _detect_new_columns(self, info: BatchInfo, columns_before: dict[str, str]) -> list[tuple[str, str]]:
        """Find the columns Snowflake added while loading this batch.

        This only OBSERVES. The columns were created by Snowflake during COPY.

        The table is re-read only when the batch contained a field name that
        was not a column before the load; an ordinary batch costs no extra
        call. Column names in Snowflake are compared in upper case, which is
        what ``transform.normalise_field_name`` produces.
        """
        if not (info.column_names - set(columns_before)):
            return []
        try:
            columns_after = self.describe_columns()
        except snowflake.connector.Error:
            # The data is loaded; only the observation failed. Forget the
            # cache so the next batch re-reads the columns.
            logger.warning("Could not re-read columns after load", exc_info=True)
            self._known_columns = None
            return []
        self._known_columns = columns_after
        added = [(name, data_type) for name, data_type in columns_after.items() if name not in columns_before]
        for name, data_type in added:
            logger.info("Schema evolution: Snowflake added column %s %s to %s.", name, data_type, self.table)
        return added

    def _write_audit_logs(self, result: LoadResult, info: BatchInfo) -> None:
        """Write the batch log row and one schema-evolution row per new column.

        These are application-level audit tables. A failure to write them
        must not fail the batch: the data is already in the target table, and
        raising here would make the consumer load the same file again.
        """
        try:
            cursor = self._cursor()
            try:
                # Values are passed as bind variables (%s), never built into
                # the SQL text. Only validated object names are interpolated.
                cursor.execute(
                    f"INSERT INTO {settings.SNOWFLAKE_BATCH_LOG_TABLE} ("
                    "BATCH_ID, TARGET_TABLE, FILE_NAME, KAFKA_TOPIC, OFFSET_RANGES, RECORD_COUNT, "
                    "ROWS_PARSED, ROWS_LOADED, ERRORS_SEEN, FIRST_ERROR, COPY_STATUS, COPY_QUERY_ID, "
                    "NEW_COLUMNS, LOAD_SECONDS, LOGGED_AT) "
                    "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, SYSDATE())",
                    (
                        result.batch_id, self.table, result.file_name, info.topic,
                        info.offset_ranges_text, info.record_count,
                        result.rows_parsed, result.rows_loaded, result.errors_seen,
                        result.first_error, result.status, result.query_id,
                        ",".join(name for name, _ in result.new_columns) or None,
                        result.load_seconds,
                    ),
                )
                for name, data_type in result.new_columns:
                    partition, offset = info.first_seen.get(name, (None, None))
                    cursor.execute(
                        f"INSERT INTO {settings.SNOWFLAKE_SCHEMA_LOG_TABLE} ("
                        "TARGET_TABLE, COLUMN_NAME, DATA_TYPE, BATCH_ID, FILE_NAME, "
                        "FIRST_SEEN_PARTITION, FIRST_SEEN_OFFSET, DETECTED_AT) "
                        "VALUES (%s, %s, %s, %s, %s, %s, %s, SYSDATE())",
                        (self.table, name, data_type, result.batch_id, result.file_name, partition, offset),
                    )
            finally:
                cursor.close()
        except snowflake.connector.Error:
            logger.warning("Batch %s loaded, but its audit rows could not be written", result.batch_id, exc_info=True)
            self.reset_connection()
