-- =============================================================================
-- Assignment 8 - Employee Manager
-- 01_create_objects.sql : schema and EMPLOYEES table
--
-- Safe to run again: every statement uses IF NOT EXISTS, so existing objects
-- and their data are left untouched.
-- Run with:  snow sql -c <connection> -f sql/01_create_objects.sql
-- =============================================================================

-- The schema lives in the existing AI_OPERATOR_DB database, which the working
-- role owns. (That role cannot create a new database.)
CREATE SCHEMA IF NOT EXISTS AI_OPERATOR_DB.EMPLOYEE_APP
    COMMENT = 'Assignment 8: Streamlit employee application';

-- One row per employee. The column types were chosen so the Add/Edit form can
-- use a matching Streamlit widget for each one (text, number, date, boolean,
-- single choice, multiple choice, long text).
CREATE TABLE IF NOT EXISTS AI_OPERATOR_DB.EMPLOYEE_APP.EMPLOYEES (
    -- Surrogate key generated by Snowflake; never typed in by a user.
    EMPLOYEE_ID       NUMBER(10,0)   NOT NULL AUTOINCREMENT START 1001 INCREMENT 1 ORDER,

    -- Personal details
    FIRST_NAME        VARCHAR(50)    NOT NULL,
    LAST_NAME         VARCHAR(50)    NOT NULL,
    EMAIL             VARCHAR(120)   NOT NULL,   -- stored in lower case
    PHONE             VARCHAR(20),               -- optional
    GENDER            VARCHAR(20)    NOT NULL,
    DATE_OF_BIRTH     DATE           NOT NULL,

    -- Job details
    DEPARTMENT        VARCHAR(50)    NOT NULL,
    JOB_TITLE         VARCHAR(80)    NOT NULL,
    EMPLOYMENT_TYPE   VARCHAR(20)    NOT NULL,   -- Full-time / Part-time / Contract / Intern
    WORK_LOCATION     VARCHAR(50)    NOT NULL,
    HIRE_DATE         DATE           NOT NULL,
    SALARY            NUMBER(12,2)   NOT NULL,   -- annual salary in INR
    EXPERIENCE_YEARS  NUMBER(4,1)    NOT NULL,   -- total professional experience
    SKILLS            ARRAY          NOT NULL DEFAULT ARRAY_CONSTRUCT(),

    -- Flags
    IS_ACTIVE         BOOLEAN        NOT NULL DEFAULT TRUE,    -- currently employed
    IS_REMOTE         BOOLEAN        NOT NULL DEFAULT FALSE,   -- works remotely

    -- Free text
    NOTES             VARCHAR(1000),

    -- Row timestamps: set on insert; the app also sets UPDATED_AT on update.
    CREATED_AT        TIMESTAMP_LTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT        TIMESTAMP_LTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    -- Snowflake records these constraints but does not enforce them on
    -- standard tables, so the app checks e-mail uniqueness before each write.
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UQ_EMPLOYEES_EMAIL UNIQUE (EMAIL)
)
COMMENT = 'Employees managed by the Employee Manager Streamlit app';
